### PR TITLE
feat(verification): Verification email code mutation

### PR DESCRIPTION
**Pull request by Josue19-08**
# Pull Request for SafeTrust - Close Issue https://github.com/safetrustcr/Frontend/issues/94

❗ **Pull Request Information**

This pull request addresses the implementation of the verification system for the email verification page. The previous system lacked a clear method for validating the code, so this issue focused on adding the necessary logic to handle both successful verification and errors (invalid or expired code).

## 🌀 Summary of Changes

- **Implemented the verification code logic** on the email verification page. Now, a clear message is displayed based on the verification result.
- **Added detailed error handling**, showing appropriate error messages in case the verification code is invalid or has expired.
- **Improved the user interface**, displaying success or error messages prominently, enhancing the user experience during the code verification process.

### Evidence Before the Solution

Before applying the solution, the verification page lacked a functional system for validating the code, which caused confusion for users as they were not informed if the code was incorrect or expired.

### Evidence After the Solution

After applying the solution, the page now displays clear messages regarding the verification status. If the code is valid, a success message is shown. If the code is invalid or expired, an error message is displayed, providing clear feedback to the user.

- **Video**: [Link to Loom video](https://www.loom.com/share/0dc665bd981946f6b7871ac7f4bfc19d?sid=561a273f-b241-441b-83fa-2eddae46280a)

## 📂 Related Issue

This pull request will close issue [#94](https://github.com/safetrustcr/Frontend/issues/94) upon merging.

---

🎉 Thank you for reviewing this PR! 🎉

### CODE REVIEW

**Comment by zleypner** [comment]
Hello @Josue19-08! 👋 I am reviewing your PR. 📝 Thank you for your contribution! 🚀

**Comment by Josue19-08** [comment]
Hello @zleypner. Great, I'll keep an eye out, Sir.

**Comment by zleypner** [comment]
Hello @Josue19-08 !
As per our conversation on Telegram and the requested code changes, please proceed to upload the changes, upload the video with more details about hasura setup and submit the pull request. Once the PR is ready, I'll conduct a final review.

Thank you!

**Comment by Josue19-08** [comment]
@zleypner working on it Sir

**Comment by Josue19-08** [comment]
@zleypner 
Changes Made in the Code

 1. Update to the GraphQL Client
In the file `email-verification/page.tsx`, the configuration of the GraphQL client was updated to explicitly include the required headers. This ensures a secure connection to the Hasura server. The implementation now uses the admin key (`x-hasura-admin-secret`) for authentication:

```javascript
const graphQLClient = new GraphQLClient("http://localhost:8080/v1/graphql", {
  headers: {
    "x-hasura-admin-secret": "my**********", 
  },
});
```

Demo Video:
https://www.loom.com/share/0dc665bd981946f6b7871ac7f4bfc19d?sid=049a1ebe-3a9e-4f1

**Comment by zleypner** [comment]
@Josue19-08 ,

As feedback, I want to thank you for always answering questions and being so responsive. 🙌 It truly shows your dedication as a professional. 💼 Also, thank you for your valuable contribution to our project. 🚀

I will now proceed to merge this PR. ✅

**Comment by Josue19-08** [comment]
Thank you very much @zleypner, it was a pleasure to contribute to this project. ❤️‍🔥✨️🫡

**Pull request merged**
