### PR TITLE
Feat/integrate biome for code formatting and linting

### LINKED ISSUE #86: Integrate Biome for Code Formatting and Linting
# Integrate Biome for Code Formatting and Linting
Implement Biome as our unified code formatter and linter to improve code quality, consistency, and developer experience in our project

## Problem

We need to create a mechanism to format the code when pushing commits to improve the readability and developer's experience

## Solution

- Install Biome as a dev dependency
- Configure Biome for:
  - Code formatting
  - Linting for React, TypeScript, and JavaScript
  - Integration with our existing tech stack
- Update project scripts
- Create configuration file

## Implementation Steps
1. Install Biome
```bash
npm install --save-dev @biomejs/biome
```

2. Create Biome configuration file `biome.json`
3. Add scripts to `package.json`:
```json
{
  "scripts": {
    "format": "biome format --write ./src",
    "lint": "biome lint ./src",
    "check": "biome check ./src"
  }
}
```

4. Configure pre-commit hooks with Husky/lint-staged (optional)

## Expected Benefits
- Faster code formatting and linting
- Reduced bundle size by replacing multiple tools
- Consistent code style across the project
- Improved developer productivity

## Potential Challenges
- Migration from existing ESLint/Prettier configurations
- Potential minor syntax adjustment requirements

## Tasks
- [ ] Research Biome configuration for our specific tech stack
- [ ] Implement initial configuration
- [ ] Test integration in development environment
- [ ] Make a video showing the issue solved

## Additional notes

Please, consider guiding you from this project: https://github.com/Vagabonds-Labs/cofiblocks

### PR DESCRIPTION
**Pull request by 0xdevcollins**
# Pull Request for SafeTrust - Close Issue

❗ **Pull Request Information**

This pull request integrates Biome as the unified code formatter and linter for our project to improve code quality, consistency, and developer experience.

## 🌀 Summary of Changes

Installed Biome as a dev dependency (@biomejs/biome).
Created a biome.json configuration file with appropriate settings for code formatting and linting tailored for React, TypeScript, and JavaScript.
Updated package.json scripts to include commands for formatting (npm run format), linting (npm run lint), and checking the codebase (npm run check).
Configured Husky and lint-staged for pre-commit hooks to automatically format and lint code before commits.

This pull request will **close #86 ** upon merging.

---

🎉 Thank you for reviewing this PR! 🎉

### CODE REVIEW

**Comment by diegoTech14** [comment]
@0xdevcollins Hello sir, I'm here supporting Randy, the PR looks good, we just need to apply the formatting only to the prepared files, not the entire `src` directory. 🚀

**Comment by 0xdevcollins** [comment]
Okay, I will modify it.

**Comment by 0xdevcollins** [comment]
@diegoTech14 Please check

**Comment by diegoTech14** [comment]
> @diegoTech14 Please check 

I will check sir, thank you

**Comment by DiegoB1911** [comment]
Hi @0xdevcollins, great work! Could you just resolve the conflicts, please?

**Comment by 0xdevcollins** [comment]
Okay

**Comment by 0xdevcollins** [comment]
@DiegoB1911 I have resolved the conflict

**Comment by diegoTech14** [comment]
@0xdevcollins Hello friend, thanks for your great work, you just need to resolve some conflicts and then we will merge. 🚀

**Comment by JosueBrenes** [comment]
image

**Comment by 0xdevcollins** [comment]
please merge this before merging others. My pr is formatting the code so if any other pr is merged be fore mine, there's definitely gonna be a conflict

**Comment by diegoTech14** [comment]
@0xdevcollins Hey man, thanks for great work! merged

**Pull request merged**
