### PR TITLE
Set up Testing Infrastructure with Jest and Testing Library

### LINKED ISSUE #90: Set up Testing Infrastructure with Jest and Testing Library
# [Frontend] Set up Testing Infrastructure with Jest and Testing Library

Set up comprehensive testing infrastructure for our React frontend application, including unit tests, component tests, and integration tests.

## Problem
We need to:
- Set up Jest for unit testing
- Configure React Testing Library for component testing
- Add MSW for API mocking
- Set up test coverage reporting
- Implement E2E testing capabilities

### Package Installation
```bash
# Core testing libraries
npm install --save-dev jest @testing-library/react @testing-library/jest-dom @testing-library/user-event
npm install --save-dev @jest/types jest-environment-jsdom

# For API mocking
npm install --save-dev msw

# For component snapshot testing
npm install --save-dev @testing-library/jest-dom

# For coverage reporting
npm install --save-dev @types/jest jest-coverage-badges

# For E2E testing
npm install --save-dev cypress @testing-library/cypress
```

### Configuration Files

```javascript
// jest.config.js
module.exports = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(gif|ttf|eot|svg|png)$': '<rootDir>/test/__mocks__/fileMock.js',
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.d.ts',
    '!src/mocks/**',
    '!src/stories/**'
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80
    }
  }
};
```

```typescript
// src/setupTests.ts
import '@testing-library/jest-dom';
import { server } from './mocks/server';

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());
```

```typescript
// src/test-utils.tsx
import { render } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter } from 'react-router-dom';

const AllTheProviders = ({ children }) => {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
      },
    },
  });

  return (
    <QueryClientProvider client={queryClient}>
      <BrowserRouter>
        {children}
      </BrowserRouter>
    </QueryClientProvider>
  );
};

const customRender = (ui, options = {}) =>
  render(ui, { wrapper: AllTheProviders, ...options });

export * from '@testing-library/react';
export { customRender as render };
```

### MSW Setup for API Mocking

```typescript
// src/mocks/handlers.ts
import { graphql } from 'msw';

export const handlers = [
  graphql.query('GetUserProfile', (req, res, ctx) => {
    return res(
      ctx.data({
        users_by_pk: {
          id: '1',
          email: 'test@example.com',
          first_name: 'Test',
          last_name: 'User'
        }
      })
    );
  }),
  
  graphql.mutation('UpdateUserProfile', (req, res, ctx) => {
    const { data } = req.variables;
    return res(
      ctx.data({
        update_users_by_pk: {
          ...data,
          id: '1'
        }
      })
    );
  })
];
```

### Example Test Cases

```typescript
// src/components/UserProfile/UserProfile.test.tsx
import { screen, render, waitFor } from '@/test-utils';
import userEvent from '@testing-library/user-event';
import { UserProfile } from './UserProfile';

describe('UserProfile', () => {
  it('renders user information correctly', async () => {
    render(<UserProfile userId="1" />);
    
    await waitFor(() => {
      expect(screen.getByText('Test User')).toBeInTheDocument();
    });
  });

  it('handles profile update', async () => {
    render(<UserProfile userId="1" />);
    
    await userEvent.type(
      screen.getByLabelText(/first name/i),
      'Updated'
    );
    
    await userEvent.click(screen.getByRole('button', { name: /save/i }));
    
    await waitFor(() => {
      expect(screen.getByText('Profile updated')).toBeInTheDocument();
    });
  });
});
```

### Scripts to Add in package.json
```json
{
  "scripts": {
    "test": "jest",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage",
    "test:e2e": "cypress open",
    "test:e2e:headless": "cypress run"
  }
}
```

## Success Criteria
- [ ] All test configurations working
- [ ] MSW mocking GraphQL requests
- [ ] Coverage reporting set up
- [ ] CI integration ready
- [ ] E2E testing framework configured
- [ ] Documentation added

## Prerequisites
- [ ] React project set up
- [ ] TypeScript configured
- [ ] GraphQL client implemented

### PR DESCRIPTION
**Pull request by Michaelkingsdev**
# Pull Request for SafeTrust - Close Issue

❗ **Pull Request Information**

## 🌀 Summary of Changes

- [x] All test configurations working
- [ ] MSW mocking GraphQL requests
- [x] Coverage reporting set up
- [ ] CI integration ready
- [x] E2E testing framework configured
- [ ] Documentation added

## 📂 Related Issue

This pull request will close #90 upon merging.

---

🎉 Thank you for reviewing this PR! 🎉

### CODE REVIEW

**Comment by Michaelkingsdev** [comment]
@JosueBrenes Please i am still working on this. I just updated my PR. But will push the final PR soon.

**Comment by JosueBrenes** [comment]
Hi @Michaelkingsdev let me know when you have it ready

**Comment by Michaelkingsdev** [comment]
> Hi @Michaelkingsdev let me know when you have it ready

Alright

**Comment by JosueBrenes** [comment]
One thing @Michaelkingsdev

image

For you to solve them.

**Comment by Michaelkingsdev** [comment]
@JosueBrenes 
## 🌀 Summary of Changes

- [x] All test configurations working
- [ ] MSW mocking GraphQL requests (msw is breaking the code so i am fixing it right away)
- [x] Coverage reporting set up
- [x] CI integration ready
- [x] E2E testing framework configured
- [x] Documentation added


## Note: Everything is working except mock service worker. Additionally, any changes i made to the entire codebase are based on lint rules, build and test i ran. Thanks

## ❗ `MSW` is in progress. Thanks

**Comment by Michaelkingsdev** [comment]
Screenshot 2024-11-27 at 9 25 53 PM
Screenshot 2024-11-28 at 7 11 58 AM

**Pull request merged**
