### PR TITLE
feat: adding i18next and react-i18next

### PR DESCRIPTION
**Pull request by QuiqueCode**
# Pull Request for SafeTrust - Close Issue

❗ **Pull Request Information**

This pull request is to implement the multi-language system to the application, allowing the internationalization of the software product.

## 🌀 Summary of Changes

-  [x] **Add i18next and react-i18next**
-  [x] **Add base folder structure**
-  [x] **Add translation resources for English and Spanish `(resources.ts)`**
-  [x] **Add i18next config `(config.ts)`**
-  [x] **Add missing export in i18next config `(config.ts)`**
-  [x] **Add function to change language `(i18n.ts)`**
-  [x] **Add language switch button component `(LanguageSwitcher.ts)`**
-  [x] **Add language  translation for LanguageSwitcher component `(resources.ts)`**
-  [x] **Add translations for "My apartments" view `(resources.ts)`**
-  [x] **Add translations for "Interested People" view `(resources.ts)`**
-  [x] **Add missing translations for "Interested People" view `(resources.ts)`**
-  [x] **Clean up and refactor translations for "Interested People" view `(resources.ts)`**
-  [x] **Add translations for "Email verification" `(resources.ts)`**
-  [x] **Add missing translation keys `(resources.ts)`**
-  [x] **Add translations for user profile section ` profile/ (page.tsx, AccountOverview.tsx, ProfileForm.tsx, Sidebar.tsx)` and configure i18n import config in ` (layout.tsx)` to support the translation integration**
-  [x] **Add translations for user home section` home/ (PropertyList.tsx, PropertyCard.tsx)`**
-  [x] **Add translations for house section` house/ (PropertyDetails.tsx, SideBar.tsx)`**
-  [x] **Add translations for my apartments section` my-apartments/ (page.tsx)` ` pages/ (ApartmentsComponent.tsx)`**
-  [x] **Update translation file ` (resources.ts)`**
-  [x] **Add translations for interested people section` interested-people/ (page.tsx, useSearchAndFilter.ts)` 
` interestedPeople/ (DropdoenPagination.tsx, SearchAndFilter.tsx, ApartmentDetails.tsx)` ` components/ (Table.tsx)`**
-  [x] **Update status in view and translations ` (resources.ts)  components / (Table.tsx)`**
-  [x] **Add language switch, flags in navbar and fix minor bug ` layouts/ (Header.tss)  language / (LanguageSwitcher.tsx)`**
-  [x] **Add translations for category sidebar` layouts/ (Sidebar.tsx)`**
-  [x] **Add translations for email verification` email-verification/ (page.tsx)`**
-  [x] **Add reservation toast translations` escrow/ (useBookReservation) i18n/ (resources.ts)`**
### Evidence Before Solution

- **Video**: [Link to Loom video](https://www.loom.com/share/abef94d9fb824ece8cd88bb13cf683ab?sid=34d6c6d6-8b2e-4368-acae-234010ccf7a8)

### Evidence After Solution

- **Video**: [Link to Loom video](https://www.loom.com/share/a60fa2fa2e084549824331faa9005135?sid=b8e323bf-b561-43be-8d5c-ebd948cfbcc1)

## 📂 Related Issue

This pull request will close - #73  upon merging.

---

🎉 Thank you for reviewing this PR! 🎉

### CODE REVIEW

**Comment by zleypner** [comment]
As per our conversation, you have completed the requested tasks.

However, the Loom video is still pending. 🎥

I will proceed to review the code as soon as possible...

**Comment by QuiqueCode** [comment]
Hello @zleypner 
I’ve uploaded the Loom videos as requested. 🎥
I’m waiting for any feedback or code review.
Best regards.

**Review by zleypner — COMMENTED** [review]
Finished reviewing all changes and commits. Everything looks good! 🚀 
Good to go please set the PR to proceed merging. Thank you for your contribution! 🙌✨

**Comment by zleypner** [comment]
@QuiqueCode thanks for your effort and dedication much appreciated!

**Comment by QuiqueCode** [comment]
@zleypner Thank you! Your feedback and support mean a lot. I’m glad I could contribute effectively.

**Comment by QuiqueCode** [comment]
Hello @zleypner, all merge conflicts have been resolved, and the email verification view translations have been re-added, along with a few new ones.

**Comment by zleypner** [comment]
@QuiqueCode Thank you so much! I'll proceed to review the PR now.

**Pull request merged**
