### PR TITLE
Refactor: Migrate Icons to React Icons 

### LINKED ISSUE #132: Migrate Icons to React Icons
# Migrate Icons to React Icons

## Description

Replace the following image files with equivalent icons from React Icons:

- `Frontend\public\img\Icon.svg`
- `Frontend\public\img\icon1.jpg`
- `Frontend\public\img\icon2.jpg`

Update the corresponding components to use React Icons instead of the image files.

## Migration Details

- **`Icon.svg`** should be replaced in the following locations:
  - `Frontend\src\components\auth\NewPassword\PasswordHeader.tsx`
  - `Frontend\src\components\auth\ForgotPassword\ForgotPasswordCard.tsx`

- **`icon1.jpg`** (image 1) should be replaced with a React Icon equivalent in:
  - `Frontend\src\components\bids\ProcessTimeline\index.tsx`

- **`icon2.jpg`** (image 2) should be replaced with a React Icon equivalent in:
  - `Frontend\src\components\bids\ProcessTimeline\index.tsx`

## Steps to Complete

1. Identify suitable React Icons to replace `Icon.svg`, `icon1.jpg` (image 1), and `icon2.jpg` (image 2).
2. Import the selected React Icons into the specified files.
3. Replace the image references with the imported React Icons.
4. Ensure the new icons are styled appropriately to match the original design.
5. Test all updated components to confirm proper functionality and appearance.
6. Commit and push the changes to the repository.

## Acceptance Criteria

- [ ] `Icon.svg`, `icon1.jpg`, and `icon2.jpg` are successfully replaced with React Icons.
- [ ] The specified components are updated to use React Icons instead of the image files.
- [ ] The new icons are styled correctly and match the original design.
- [ ] No errors or visual inconsistencies are present after the migration.

### PR DESCRIPTION
**Pull request by SimplementeCao**
# Pull Request for SafeTrust - Close Issue

❗ **Pull Request Information**

Replace the following image files with equivalent icons from React Icons:

    Frontend\public\img\Icon.svg
    Frontend\public\img\icon1.jpg
    Frontend\public\img\icon2.jpg

React Icon equivalents:

image

image

image

## 🌀 Summary of Changes

- **Add here the changes**:
-  Import new React Icon
-  Use new React icon changing the labels

- **More changes**:
- Deleted the Icon.svg file
- Deleted the icon1.png file
- Deleted the icon2.png file

### Evidence Before Solution

- **Video**: [Link to Loom video](https://loom.com)

### Evidence After Solution

- **Video**: [Link to Loom video](https://loom.com)

## 📂 Related Issue

This pull request will **close #132  ** upon merging.

---

🎉 Thank you for reviewing this PR! 🎉

### CODE REVIEW

**Comment by zleypner** [comment]
Hello @SimplementeCao , I will proceed to review asap.

**Comment by zleypner** [comment]
Hello @SimplementeCao , Please update the commits based in the Git Guideline.

https://github.com/safetrustcr/Frontend/issues/35

**Comment by SimplementeCao** [comment]
hi @zleypner I have already made the changes in the commit, thx

**Comment by zleypner** [comment]
Awesome, Thank You! Checking.

**Comment by zleypner** [comment]
@SimplementeCao Would you be so kind to please add the Evidence After Solution. Thank you!
Video: [Link to Loom video](https://loom.com/)

**Comment by zleypner** [comment]
Hello @SimplementeCao , Please resolve the conflicts.

**Comment by zleypner** [comment]
Hello @SimplementeCao ! Would you be so kind to proceed with the updates requested?

**Review by zleypner — APPROVED** [review]

**Pull request merged**
