### PR TITLE
Reset Password View Implementation

### LINKED ISSUE #87: Create "Reset password" view
# Create "Reset password" View
This view is required to give the user the ability to receive a temporary password via email

## Problem
There is currently no interface for reset password 

## Solution
Develop the "Reset password" page following the design in the provided mockup: image

### Technical Specifications
- The view must be responsive

### UI/UX Considerations
- [ ] Ensure the design is visually consistent with the platform's style
- [ ] Highlight the "Send password" button for better visibility
- [ ] Use fresh password and arrow icons

## Acceptance Criteria
1. The UI/UX it's very faithful to the figma
2. Colors are the same to the figma

### PR DESCRIPTION
**Pull request by akintewe**
This PR implements the Reset Password view following the provided design mockup. The implementation includes a responsive layout, proper form handling, and matches the Figma design specifications.

What i did:
- Added ForgotPasswordCard component
- Added Reset Password page

Design Implementation:
- Implemented responsive layout
- Added city background illustrations
- Matched Figma color scheme (#F47521)

Screenshot 2024-11-22 at 11 19 35 PM
r form styling with underline input

Loom Videos:

Before: 
https://www.loom.com/share/455032a3531a49ef9bf22f9e1b05ff4d?sid=716190ee-3ae7-4fbc-b25b-e1a194669d94

After:
https://www.loom.com/share/77eb25a68fe5446aa7e0105b840e62c0?sid=b7aa3bab-a5fa-40dd-86ae-e022aa26f6ff

Closes #87

### CODE REVIEW

**Comment by zleypner** [comment]
Hello @akintewe would you be so kind to please add the Loom videos mentioned in the PR template.

https://github.com/safetrustcr/Frontend/blob/main/.github/pull_request_template.md

**Comment by akintewe** [comment]
Sure no problem

**Comment by zleypner** [comment]
Hello @akintewe , Please ensure you're following our [Branch Naming Convention](https://github.com/safetrustcr/Frontend/blob/main/GIT_GUIDELINE.md) when creating new branches, also make sure you do the atomic commits 🌳

Thank you so much for adding the loom video! Let me know if you need any help. 🚀
Feel free to contact me if you have any questions. [Telegram] (https://t.me/anwar_zlcr)

**Comment by akintewe** [comment]
> Hello @akintewe , Please ensure you're following our [Branch Naming Convention](https://github.com/safetrustcr/Frontend/blob/main/GIT_GUIDELINE.md) when creating new branches, also make sure you do the atomic commits 🌳
> 
> Thank you so much for adding the loom video! Let me know if you need any help. 🚀 Feel free to contact me if you have any questions. [Telegram](https://t.me/anwar_zlcr)

Hello sure i will do that, thank you so much

**Comment by zleypner** [comment]
Thank you so much for uploading the Loom video, @akintewe! We are almost done.

**Pull request closed without merging**
