### PR TITLE
Feat implement paid state bid request page

### PR DESCRIPTION
**Pull request by KevinMB0220**
# **Pull Request for SafeTrust - Close Issue**

## ❗ **Pull Request Information**
This Pull Request implements the **"Paid State Bid Request"** page based on the provided design mockup, addressing the requirements and functionality described in the issue.

### **Main Changes Made:**
- Created the main page component `page.tsx` in `app/bids/pages`.
- Developed the following components in `src/components/bids`:
  - `InvoiceDetails` (`index.tsx`)
  - `InvoiceHeader` (`index.tsx`)
  - `NotesSection` (`index.tsx`)
  - `ProcessTimeline` (`index.tsx`)
- Added static (hardcoded) data as placeholders until the backend connection is established.
- Designed and implemented a two-column layout with responsive design.
- Configured loading states and error handling.
- Styling aligned with the design mockup:
  - **Consistent colors:** background, text, and secondary elements.
  - **Typography and spacing:** adjusted as per the design.

## 📂 **Related Issue**
This Pull Request resolves **#69** by implementing the **"Paid State Bid Request"** page with all required functionality.

---

### CODE REVIEW

**Comment by JosueBrenes** [comment]
Hi @KevinMB0220 please resolve conflicts

image

**Comment by KevinMB0220** [comment]
> Hi @KevinMB0220 please resolve conflicts
> 
> image

Ready

**Comment by JosueBrenes** [comment]
Hi @KevinMB0220 please resolve conflicts pls

image

**Comment by KevinMB0220** [comment]
@JosueBrenes ready

**Pull request merged**
